/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pram' at '11/04/15 17:37' with Gradle 1.12
 *
 * @author pram, @date 11/04/15 17:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
